### ISSUE TITLE
jekyll 3.7.3 | Error:  SyntaxError: Unexpected token: operator (>)

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#878]
Getting this error when I run "bundle exec jekyll serve". Started after I pulled in yesterdays updates. Not sure what is the reason here, there are no line numbers or anything. Any help on how to diagnose this?

```
D:\dev\acceptbitcoincash>bundle exec jekyll serve
Configuration file: D:/dev/acceptbitcoincash/_config.yml
            Source: D:/dev/acceptbitcoincash
       Destination: D:/dev/acceptbitcoincash/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.7.3 | Error:  SyntaxError: Unexpected token: operator (>)

D:\dev\acceptbitcoincash>
```

I did have to do a "bundle install" after pulling.

**Comment by EchterAgo** [comment]
Managed to get some more info:

```
JS_Parse_Error.get (C:\Users\axel\AppData\Local\Temp\execjs20180426-20872-3gi83kjs:3538:621): SyntaxError: Unexpected token: operator (>) (ExecJS::RuntimeError)
        from C:\Users\axel\AppData\Local\Temp\execjs20180426-20872-3gi83kjs:4060:48
        from C:\Users\axel\AppData\Local\Temp\execjs20180426-20872-3gi83kjs:1:102
        from Object.<anonymous> (C:\Users\axel\AppData\Local\Temp\execjs20180426-20872-3gi83kjs:1:120)
        from Module._compile (module.js:652:30)
        from Object.Module._extensions..js (module.js:663:10)
        from Module.load (module.js:565:32)
        from tryModuleLoad (module.js:505:12)
        from Function.Module._load (module.js:497:3)
        from Function.Module.runMain (module.js:693:10)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:46:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/uglifier-3.2.0/lib/uglifier.rb:195:in `run_uglifyjs'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/uglifier-3.2.0/lib/uglifier.rb:157:in `compile'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-minifier-0.1.5/lib/jekyll-minifier.rb:53:in `output_js'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-minifier-0.1.5/lib/jekyll-minifier.rb:123:in `write'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:208:in `block in write'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:329:in `block (2 levels) in each_site_file'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:328:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:328:in `block in each_site_file'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:327:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:327:in `each_site_file'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:207:in `write'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:75:in `process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `block in start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby24-x64/bin/jekyll:23:in `load'
        from C:/Ruby24-x64/bin/jekyll:23:in `<main>'
```

**Comment by EchterAgo** [comment]
Verbose output:

```
D:\dev\acceptbitcoincash>bundle exec jekyll serve -V
  Logging at level: debug
Configuration file: D:/dev/acceptbitcoincash/_config.yml
  Logging at level: debug
      GitHub Pages: github-pages v180
      GitHub Pages: jekyll v3.7.3
         Requiring: jekyll-seo-tag
         Requiring: jekyll-github-metadata
Dotenv not found. Skipping
         Requiring: jekyll-seo-tag
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
   GitHub Metadata: Initializing...
            Source: D:/dev/acceptbitcoincash
       Destination: D:/dev/acceptbitcoincash/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       EntryFilter: excluded /CNAME
       EntryFilter: excluded /CONTRIBUTING.md
       EntryFilter: excluded /Dockerfile
       EntryFilter: excluded /EXCLUSION.md
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
       EntryFilter: excluded /kube
       EntryFilter: excluded /LICENSE
       EntryFilter: excluded /nginx.conf
       EntryFilter: excluded /Rakefile
       EntryFilter: excluded /README.md
       EntryFilter: excluded /scripts
       EntryFilter: excluded /verify.rb
       EntryFilter: excluded /websites_schema.yml
        Generating: JekyllOptionalFrontMatter::Generator finished in 0.0 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 0.000986 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 0.0 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.0 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 0.0 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 0.0 seconds.
         Rendering: adoption.html
  Pre-Render Hooks: adoption.html
  Rendering Liquid: adoption.html
  Rendering Markup: adoption.html
  Rendering Layout: adoption.html
         Rendering: adult.html
  Pre-Render Hooks: adult.html
  Rendering Liquid: adult.html
  Rendering Markup: adult.html
  Rendering Layout: adult.html
         Rendering: data.json
  Pre-Render Hooks: data.json
  Rendering Liquid: data.json
  Rendering Markup: data.json
  Rendering Layout: data.json
         Rendering: donations.html
  Pre-Render Hooks: donations.html
  Rendering Liquid: donations.html
  Rendering Markup: donations.html
  Rendering Layout: donations.html
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
  Rendering Layout: index.html
         Rendering: js/main.js
  Pre-Render Hooks: js/main.js
  Rendering Liquid: js/main.js
  Rendering Markup: js/main.js
  Rendering Layout: js/main.js
         Rendering: css/search-style.scss
  Pre-Render Hooks: css/search-style.scss
  Rendering Liquid: css/search-style.scss
  Rendering Markup: css/search-style.scss
         Rendering: stats.json
  Pre-Render Hooks: stats.json
  Rendering Liquid: stats.json
  Rendering Markup: stats.json
  Rendering Layout: stats.json
         Rendering: css/style.scss
  Pre-Render Hooks: css/style.scss
  Rendering Liquid: css/style.scss
  Rendering Markup: css/style.scss
         Rendering: assets/css/style.scss
  Pre-Render Hooks: assets/css/style.scss
  Rendering Liquid: assets/css/style.scss
  Rendering Markup: assets/css/style.scss
jekyll 3.7.3 | Error:  SyntaxError: Unexpected token: operator (>)

D:\dev\acceptbitcoincash>
```

**Comment by EchterAgo** [comment]
Hrmm, resolved by doing "git clean -dfx" and then "bundle install" again.

I hate Ruby :\

**Comment by kenman345** [comment]
sorry about that, I always recommend doing that if you're having any trouble to weed out the easily fixed bugs. I've been adding a few things we need to make the site a bit easier to maintain and load faster and some side effects in this regard will happen. Just run that again nytime you have trouble and you should be good.

**Comment by kenman345** [comment]
btw, Jekyll-minifier1.6.0 only came out because I made a PR to fix this bug as it was not minifying combined JS files properly. or CSS files too. Longstadning bug I was able to squash to get our site running a little faster on loading the page
